services:
  web:
    build: .
    ports:
      - "8080:443"
      - "8081:80"
    volumes:
      - ./public:/var/www/html
      - ./tests:/var/www/tests
    env_file:
      - .env
    restart: unless-stopped
